Use requests instead of urllib
things have been unreliable lately, failing with
tarfile.ReadError: unexpected end of data

Try using a proper http library, which seems to help here.